# Generated by Django 4.2 on 2024-10-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hoadon_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.hoadon')),
            ],
        ),
    ]
