# Generated by Django 4.2 on 2024-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hoadon_steps_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
