# Generated by Django 4.2 on 2024-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hoadon_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
