# Generated by Django 4.2 on 2024-11-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_orderevent_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['time']},
        ),
    ]
