# Generated by Django 4.2 on 2024-11-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_voucher_hoadon_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_pro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
