# Generated by Django 4.2 on 2024-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_image_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_pro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
