# Generated by Django 4.2 on 2024-11-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_description_product_original_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderEvent',
        ),
    ]
