# Generated by Django 4.2 on 2024-11-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_orderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('maEvent', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.hoadon')),
            ],
            options={
                'db_table': 'home_orderevent',
                'ordering': ['time'],
            },
        ),
    ]
