# Generated by Django 4.1.12 on 2025-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ice',
            field=models.CharField(choices=[('low', 'Ít'), ('normal', 'Bình thường'), ('high', 'Nhiều')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sugar',
            field=models.CharField(choices=[('low', 'Ít'), ('normal', 'Bình thường'), ('high', 'Nhiều')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tea',
            field=models.CharField(choices=[('low', 'Ít'), ('normal', 'Bình thường'), ('high', 'Nhiều')], default='normal', max_length=10),
        ),
    ]
