# Generated by Django 4.1.12 on 2025-01-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cartitem_ice_cartitem_sugar_cartitem_tea'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='ice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='sugar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='tea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
