# Generated by Django 4.1.12 on 2025-02-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_detail_ice_detail_sugar_detail_tea'),
    ]

    operations = [
        
        
        
        
        migrations.AlterField(
            model_name='hoadon',
            name='diaChi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Thẻ tín dụng/Ghi nợ'), ('paypal', 'Paypal'), ('cod', 'Thanh toán khi nhận hàng')], default='cod', max_length=10),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang chuẩn bị'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('failed', 'Thất bại')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tongTien',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='hoadon',
            table='home_hoadon',
        ),
    ]
