# Generated by Django 4.1.12 on 2025-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_hoadon_loi_remove_hoadon_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='loi',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='event',
        ),
        migrations.AddField(
            model_name='orderevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang chuẩn bị'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('failed', 'Thất bại')], default='pending', max_length=20),
        ),
    ]
