# Generated by Django 4.1.12 on 2025-04-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_hoadon_loi_remove_hoadon_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('return', 'Chính sách đổi/trả'), ('delivery', 'Chính sách giao hàng'), ('payment', 'Chính sách thanh toán'), ('privacy', 'Chính sách bảo mật thông tin'), ('storage', 'Chính sách bảo quản thực phẩm'), ('promotion', 'Chính sách khuyến mãi'), ('cancel', 'Chính sách hủy đơn hàng')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_open_weekend', models.BooleanField(default=True)),
                ('ship_available', models.BooleanField(default=True)),
            ],
        ),
    ]
