# Generated by Django 4.1.12 on 2025-04-19 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_policy_shopinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='email',
            field=models.EmailField(default='angia9510@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='facebook_link',
            field=models.URLField(default='https://web.facebook.com/cover.man.1485'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='website',
            field=models.URLField(default='https://4f9d-171-253-136-72.ngrok-free.app/shop/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='zalo_link',
            field=models.URLField(default='https://4f9d-171-253-136-72.ngrok-free.app/shop/'),
            preserve_default=False,
        ),
    ]
